easy_admin:
    site_name: 'Ma super admin'
    entities:
        Author:
            class: App\Entity\Author
            label: 'Auteur'
            list:
                title: 'Liste des auteurs'
        Book:
            class: App\Entity\Book
            list:
                fields:
                    - { property: 'title' }
                    - { property: 'image', type: 'image', base_path: '%app.path.uploads_dir%' }